
import { Property, Broker } from "./types";

export const MOCK_BROKERS: Broker[] = [
    {
        id: "broker-1",
        name: "Ramesh Shetty",
        email: "ramesh@example.com",
        phone: "7760704400",
        brokerCode: "PD-001",
        reraNumber: "AG-12345",
        districts: ["Udupi", "Dakshina Kannada"],
        status: "approved",
        password: "password123",
        registeredAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
        subscriptionExpiry: new Date(Date.now() + 35 * 24 * 60 * 60 * 1000).toISOString(),
        referralCode: "RAMESH123",
        referralsCount: 2,
    },
    {
        id: "broker-2",
        name: "Suresh Rao",
        email: "suresh@example.com",
        phone: "9123456780",
        brokerCode: "PD-002",
        districts: ["Moodbidri"],
        status: "pending",
        password: "password123",
        registeredAt: new Date().toISOString(),
        subscriptionExpiry: new Date(Date.now() + 45 * 24 * 60 * 60 * 1000).toISOString(),
        referralCode: "SURESH456",
        referralsCount: 0,
    },
];

export const MOCK_PROPERTIES: Property[] = [
    {
        id: "prop-1",
        brokerId: "broker-1",
        title: "Luxury Villa in Udupi",
        description: "3BHK Villa with all amenities, near beach.",
        price: 15000000,
        district: "Udupi",
        location: "Manipal",
        type: "sale",
        category: "residential",
        images: ["https://images.unsplash.com/photo-1600596542815-e32cb5328d53?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80"],
        amenities: ["Water Supply", "Electricity", "Gated Community", "Car Parking", "Garden"],
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        expiresAt: new Date(Date.now() + 45 * 24 * 60 * 60 * 1000).toISOString(),
        isActive: true,
        likes: 12,
        leadsCount: 3,
    },
    {
        id: "prop-2",
        brokerId: "broker-1",
        title: "Commercial Space in Mangalore",
        description: "1000 sqft office space in city center.",
        price: 50000,
        district: "Dakshina Kannada",
        location: "Mangaluru",
        type: "rent",
        category: "commercial",
        images: ["https://images.unsplash.com/photo-1497366216548-37526070297c?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80"],
        amenities: ["CCTV", "Fire Safety", "Power Backup", "Lift", "Security"],
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        expiresAt: new Date(Date.now() + 40 * 24 * 60 * 60 * 1000).toISOString(),
        isActive: true,
        likes: 5,
        leadsCount: 1,
    },
];
