-- Create a table for global site settings (Banner, etc.)
CREATE TABLE IF NOT EXISTS public.site_settings (
    id bigint generated by default as identity primary key,
    key text unique not null,
    value jsonb not null,
    updated_at timestamptz default now()
);

-- Enable RLS
ALTER TABLE public.site_settings ENABLE ROW LEVEL SECURITY;

-- Policies
-- 1. Public can READ everything (needed for homepage banner)
CREATE POLICY "Public read access" 
ON public.site_settings FOR SELECT 
USING (true);

-- 2. Admins can INSERT/UPDATE
-- Using our safe is_admin() function if available, or manual check
CREATE POLICY "Admins can manage settings" 
ON public.site_settings 
FOR ALL 
USING (
    (SELECT is_admin FROM public.profiles WHERE id = auth.uid()) = true
);

-- Insert default banner config if not exists
INSERT INTO public.site_settings (key, value)
VALUES (
    'banner_config', 
    '{
        "title": "Grow Your Business with Property Dosti",
        "description": "Join 500+ verified brokers. Get exclusive leads and premium listing visibility across Karnataka districts.",
        "buttonText": "Join Premium Network",
        "buttonLink": "/signup",
        "backgroundPosition": "50% 50%",
        "backgroundImage": "" 
    }'::jsonb
)
ON CONFLICT (key) DO NOTHING;
